### ISSUE TITLE
Ho to deal with complex packaging and non-cli applications

### ISSUE THREAD

**Issue by marco-brandizi** [ctrueden/jrun#10]
Hi, 

just discovered jrun, very cool! 

I wonder if there is support (or it's planned) for cases more complex than just running the main class in a jar. For instance, I have desktop applications that need to install config and data directories, I'd like to manage both the case of shared config directories and user-specific directories. Should jrun deal with it, or is there some other library that I should use in my application?

Moreover, I would be interested in Maven projects that are not executables, but, for instance, provide a .war file and a script to install it on your application server (eg, Tomcat), and possibly linking dependencies in .m2.

**Comment by ctrueden** [comment]
@marco-brandizi wrote:
> I wonder if there is support (or it's planned) for cases more complex than just running the main class in a jar. For instance, I have desktop applications that need to install config and data directories

There are several different Java application packaging tools intended for end-user application deployment. IMHO, without having exhaustively surveyed all options, the most promising one right now is the JavaFX packager which comes standard with the JDK now. Note that this is a distinct thing from JavaFX the RIA infrastructure and UI toolkit. There is a nice [JavaFX Maven plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) maintained @FibreFox which lets you integrate packaging into your Maven builds.

For the [ImageJ project](https://github.com/imagej/imagej), we currently use a [custom launcher](https://github.com/imagej/imagej-launcher) but maintaining it is difficult, so we are planning to switch to a [JavaFX self-contained application](http://docs.oracle.com/javafx/2/deployment/self-contained-packaging.htm), either with or without a bundled JRE/JDK. The configuration for this can be seen in the parent POM we use; see [here](https://github.com/scijava/pom-scijava-base/blob/pom-scijava-base-3.1.0/pom.xml#L474-L491) and [here](https://github.com/scijava/pom-scijava-base/blob/pom-scijava-base-3.1.0/pom.xml#L1044-L1084).

Reasons I prefer the JavaFX packager to previously available solutions:

* The JavaFX packager is a first-party solution, which is likely to continue being supported, both by Oracle and by the OpenJDK community.
* The JavaFX packager tries very hard to work from the CLI on Windows, macOS and Linux platforms, as long as you have the appropriate dev tools installed on the box. This means it is feasible to automate application deployment for all major target platforms, unlike many of the other solutions.
* The JavaFX packager is FOSS, unlike many other Java packagers.

That said, there are still pieces missing. For instance, in order to switch ImageJ from its current custom launcher to the JavaFX deployment system, we will need to either: A) enhance the JavaFX native launcher to support the features that the ImageJ launcher supports; or B) create a pure-Java launcher which relaunches the JVM with the appropriate settings depending on CLI flags passed etc. We are planning to do (B) right now, since it is generally useful, and (A) would probably be a big time investment arguing for features upstream etc. In order to accomplish (B), we will first try starting from an existing solution like [Apache Commons Launcher](https://commons.apache.org/proper/commons-launcher/).

> I'd like to manage both the case of shared config directories and user-specific directories.

Indeed, ImageJ needs this too: we want to support shared/system plugins as well as plugins installed in user space. Perhaps the tool for managing that should be its own shared library. This is an area where I think Java is lacking—people each seem to invent their own solutions along these lines, the Java Preferences API has serious issues, etc.—but the use cases are very heterogeneous so I don't have a good idea on how to improve the situation.

> I would be interested in Maven projects that are not executables, but, for instance, provide a .war file and a script to install it on your application server (eg, Tomcat), and possibly linking dependencies in .m2.

This sounds like something where jrun could potentially be helpful. Unfortunately, I have only limited experience with Java application servers, so I'm not familiar with existing deployment solutions for .war files. I do know that historically on the Maven users list there have been a lot of questions about .war deployment—mostly people trying to shoehorn Maven into a tool to do that, and the community pushing back against it.

One easy thing which occurs to me is to add a flag to jrun which does all the environment setup, but does not actually launch the thing at the end. That way, you could feed it a .war endpoint and let it link in all the deps, and then it could echo the cached environment directory to stdout at the end or something. This would let you use jrun as a building block in your own deployment scripts. Would something like that be helpful?

Generally speaking, Java application packaging and deployment is a _huge_ can of worms and I certainly have no plans for jrun to move in that direction. It is intended to be lightweight and painless for launching software components which are already properly deployed to Maven repositories. On the other hand, if you have a specific vision for how the jrun paradigm could be easily adapted to your use cases in a better way than the options I describe above, let's continue the discussion and figure out the best way to proceed!

**Comment by FibreFoX** [comment]
> Moreover, I would be interested in Maven projects that are not executables, but, for instance, provide a .war file and a script to install it on your application server (eg, Tomcat), and possibly linking dependencies in .m2.

This sounds a bit strange, since `.war` files CAN be executable and are getting called "FAT-WARs", but have to be configured to be (and have to include some webserver like [Jetty](https://github.com/jetty-project/embedded-jetty-live-war), [Tomcat/TomEE](http://tomee.apache.org/advanced/shading/index.html#_fat_wars), [Spring](https://spring.io/guides/gs/convert-jar-to-war/) or other products).

"symlinking" would probably limited to Linux-systems, as Windows users might not be able to (I think this is limited to current NTFS filesystem implementations).

As @ctrueden said, creating "native launchers" is a big mess right now, because there are a lot of ways to do so, but only a few ones which are cross-plattform, and even that isn't the best. With the upcoming JRE/JDK 9 this will be ugly even more, because of the new packaging-concept (which I still fear to use).

**Comment by marco-brandizi** [comment]
Thanks for your replies.

I don't know JavaFX, but I'm not thinking of self-contained big bundles, to be run from the GUI, I need it more often to provide a framework of command line tools, which is composed of core components/commands and additional ones, which can be installed optionally. Both share a number of files (e.g., logging configuration), and hece the ideal pacakge manager should be ablet to unpack the new components, put in place its files (e.g., in /usr/local/my-framework), deal with overlaps, upgrades, etc. More or less like it happens with APT in Debian, Yum, MacPorts etc.

The case of .wars is similar: I'd like an installer to be able to place an application's war onto the app folder of an application server like Tomcat (location to be specified by the installing user). Ideally this should integrate with the above package manager, allowing to install additional shared files (in shared locations) and configure the application running in the .war to point it to such files.

**Comment by ctrueden** [comment]
I'm going to close this, since there are no plans to make `jrun` into a more general Java component package manager, or a non-cli tool.
